CREATE TABLE ORDER (
         ID INTEGER,
         CLIENT_ID INTEGER,
         ORDER_TIME TIMESTAMP,
         CONSTRAINT ORDER_PK PRIMARY KEY (ID)
);
 
CREATE TABLE CLIENT (
         ID INTEGER,
         NAME VARCHAR2(100),
         BITHDAY DATE,
         SEX CHAR(1),
         CONSTRAINT CLIENT_PK PRIMARY KEY (ID)
);
 
CREATE TABLE CHEQUE (
         ORDER_ID INTEGER,
         ITEM_ID INTEGER,
         QUANTITY INTEGER,
         PRICE NUMBER
);
 
CREATE TABLE ADDRESS (
         ID INTEGER,
         ADDRESS VARCHAR2(100),
         CONSTRAINT ADDRESS_PK PRIMARY KEY (ID)
);
 
CREATE TABLE C_ADDRESS (
         CLIENT_ID INTEGER,
         ADDRESS_ID INTEGER,
         IS_DEFAULT CHAR(1)
);
 
CREATE TABLE MDM.ITEM (
         ID INTEGER,
         NAME VARCHAR2(100),
         PRICE NUMBER,
         CONSTRAINT ITEM_PK PRIMARY KEY (ID)
);

